"""Create Conversion & Currency model

Revision ID: 25d8c112a5d5
Revises: 
Create Date: 2023-01-23 23:21:58.083416

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy_jsonfield

# revision identifiers, used by Alembic.
revision = "25d8c112a5d5"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversions",
        sa.Column(
            "id",
            postgresql.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("amount", sa.Float(), nullable=True),
        sa.Column("converted_amount", sa.Float(), nullable=True),
        sa.Column("rate", sa.Float(), nullable=True),
        sa.Column(
            "metadata", sqlalchemy_jsonfield.jsonfield.JSONField(), nullable=False
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_conversions_id"), "conversions", ["id"], unique=False)
    op.create_table(
        "currencies",
        sa.Column(
            "id",
            postgresql.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_currencies_id"), "currencies", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_currencies_id"), table_name="currencies")
    op.drop_table("currencies")
    op.drop_index(op.f("ix_conversions_id"), table_name="conversions")
    op.drop_table("conversions")
    # ### end Alembic commands ###
